services:
  stats-server:
    ports:
      - "9090:9090"
    build: stat/stat-server
    image: stat-server
    container_name: stat-server
    depends_on:
      stats-db:
        condition: service_healthy
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9090/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:5432/ewm-hits
      - SPRING_DATASOURCE_USERNAME=dbuser
      - SPRING_DATASOURCE_PASSWORD=12345

  stats-client:
    ports:
      - "8080:8080"
    build: stat/stat-client
    image: stat-client
    container_name: stat-client
    depends_on:
      - stats-server
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/" ]
      interval: 10s
      timeout: 5s
      retries: 5
    environment:
      - STATS_SERVER_URL=http://server:9090

  stats-db:
    image: postgres:16.1
    container_name: stats-db
    ports:
      - "5432:5432"
    volumes:
      - ./stat-postgres:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=12345
      - POSTGRES_USER=dbuser
      - POSTGRES_DB=ewm-hits
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10
