INSERT INTO users (name, email)
VALUES ('User1', 'user1@example.com'),
       ('User2', 'user2@example.com'),
       ('User3', 'user3@example.com'),
       ('User4', 'user4@example.com'),
       ('User5', 'user5@example.com'),
       ('User6', 'user6@example.com'),
       ('User7', 'user7@example.com'),
       ('User8', 'user8@example.com'),
       ('User9', 'user9@example.com'),
       ('User10', 'user10@example.com'),
       ('User11', 'user11@example.com'),
       ('User12', 'user12@example.com'),
       ('User13', 'user13@example.com'),
       ('User14', 'user14@example.com'),
       ('User15', 'user15@example.com'),
       ('User16', 'user16@example.com'),
       ('User17', 'user17@example.com'),
       ('User18', 'user18@example.com'),
       ('User19', 'user19@example.com'),
       ('User20', 'user20@example.com'),
       ('User21', 'user21@example.com'),
       ('User22', 'user22@example.com'),
       ('User23', 'user23@example.com'),
       ('User24', 'user24@example.com'),
       ('User25', 'user25@example.com');

INSERT INTO categories (name)
VALUES ('Электроника'),
       ('Бытовая техника'),
       ('Одежда'),
       ('Обувь'),
       ('Аксессуары'),
       ('Красота и здоровье'),
       ('Спорт и отдых'),
       ('Игрушки'),
       ('Детские товары'),
       ('Продукты питания'),
       ('Напитки'),
       ('Книги'),
       ('Канцелярия'),
       ('Мебель'),
       ('Освещение'),
       ('Товары для дома'),
       ('Товары для животных'),
       ('Инструменты'),
       ('Автотовары'),
       ('Строительные материалы'),
       ('Сад и огород'),
       ('Музыкальные инструменты'),
       ('Хобби и творчество'),
       ('Компьютеры и комплектующие'),
       ('Смартфоны и гаджеты');

INSERT INTO events (title, category_id)
VALUES ('Спектакль', 5);